variable "environment" {
  description = "Name of the environment; will be prefixed to all resources"
  type        = string
  default = "dev"
}

variable "project" {
  description = "Name of the project."
  type        = string
  default     = "etr"
}

variable "creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. "
  type        = string
  default     = ""
}

#
## NETWORKING
#
variable "vpc_id" {
  description = "EFS is created in this VPC"
  type        = string
  default     = ""
}

variable "subnet_ids" {
  description = "The created EFS will be available in these subnet ids"
  type        = list(string)
  default =  [ ]
}
variable "mount_target_ip_address" {
  type        = string
  description = "The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target"
  default     = null
}

#
## ENCRYPTION
#
variable "encrypted" {
  description = "Encrypt file system."
  type        = bool
  default     = true
}

variable "kms_key_id" {
  type        = string
  description = "If set, use a specific KMS key"
  default     = null
}

variable "mount_location" {
  description = "Used to create a cloud init config part for amazon linux instances."
  type        = string
  default     = "/efs"
}

variable "performance_mode" {
  description = "maxIO"
  type        = string
  default     = "generalPurpose"
}

variable "throughput_mode" {
  type        = string
  description = "Throughput mode for the file system. Defaults to bursting. Valid values: `bursting`, `provisioned`. When using `provisioned`, also set `provisioned_throughput_in_mibps`"
  default     = "bursting"
}


variable "provisioned_throughput_in_mib" {
  default     = 0
  description = "The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to provisioned"
}




variable "transition_to_ia" {
  description = "Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, or AFTER_90_DAYS."
  type        = string
  default     = "AFTER_60_DAYS"
}

variable "tags" {
  description = "A map of tags to add to the resources"
  type        = map(string)
  default     = {}
}

